Numpy tutorial can be found online at: www.tutorialspoint.com/numpy
Numpy cheat sheet https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

In [23]:
# .array() creates an array of specified values
# .dtype defines the type of value created
import numpy as np
a = np.array([1,2,3,4,5],dtype=int)
print(a)

# .arange() creates a 1D array up to specified value
a = np.arange(18)
print(a)

# .ndim() shows the total number of dimensions
print(a.ndim) 

# .reshape() allows you to change the number of dimensions
print(a.reshape(3,6))
print(a.ndim) 

# .empty() creates an empty array of specified size, initial random variables are given until they are initialised
a = np.empty([3],dtype=int)
print(a)

# .zeros()) creates an array of zeros of specified size
a = np.zeros([3,2],dtype=int)
print(a)

# .ones() creates an array of ones of specified size
a = np.ones([5,5],dtype=int)
print(a)

# .asarray() turns existing data into a np array
x = [1,2,3,4,5,6]
y = np.asarray(x,dtype=float)
print(y)

# .linspace() creates array of x number of steps, for given start and stop points
x = np.linspace(10,50,9)
print(x)
y = np.linspace(10,50,9,endpoint=False) # means final stop is not included in array
print(y)

# .flatten() can be used to reduce an array to 1D
a = np.arange(20)
a = a.reshape(5,4)
print(a)
a = a.flatten()
print(a)



# STRING FUNCTIONS

# char.capitalize() creates array with only first letter capatialised
a = np.char.capitalize(['hello, how are you?','yes','no'])
print(a)

# char.title() creates array with every string element capiltalised
a = np.char.title(['hello, how are you?','yes','no'])
print(a)

# char.multiply() creates an array of x times a given string
a = np.char.multiply(['Hello'],3)
print(a)




[1 2 3 4 5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
1
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
1
[-9223372036854775808 -8070441736889495990      140725734932482]
[[0 0]
 [0 0]
 [0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[1. 2. 3. 4. 5. 6.]
[10. 15. 20. 25. 30. 35. 40. 45. 50.]
[10.         14.44444444 18.88888889 23.33333333 27.77777778 32.22222222
 36.66666667 41.11111111 45.55555556]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
['Hello, how are you?' 'Yes' 'No']
['Hello, How Are You?' 'Yes' 'No']
['HelloHelloHello']
